version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-web-mcpmode-backend
    restart: unless-stopped
    ports:
      - "8003:8003"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      - BACKEND_PORT=8003
    volumes:
      - ./backend/data:/app/data
      - ./backend/chat_history.db:/app/chat_history.db
      - ./backend/mcp.json:/app/mcp.json
    networks:
      - ai-web-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-web-mcpmode-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ai-web-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s


networks:
  ai-web-network:
    driver: bridge
